wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1660502942.619106
    t:
      1:
      - 55
      3:
      - 23
      4: 3.10.5
      5: 0.13.1
      8:
      - 5
